### ISSUE TITLE
Null, undefined and nan

### ISSUE THREAD

**Issue by Isaac-Leonard** [alshdavid/BorrowScript#1]
How does this project plan to handle and / or implement null, undefined and nan values?
Will they remain as they are in currently in typescript or will null and undefined be merged into one value?
Will the equality stuff with nan values also be changed or will anywhere a nan may normally be produced simply throw an error?

**Comment by alshdavid** [comment]
Very good questions

> How does this project plan to handle and / or implement null, undefined

I believe simplifying Rust's model here makes sense. In Rust there are `Option<T>` types which you can use to store a `Box` to a value:
```rust
fn main() {
  let hasFoo: Option<Box<i32>> = Some(Box::new(0));
  let nullFoo: Option<Box<i32>> = None;

  println!("hasFool: {}", hasFoo.is_some());
  println!("nullFoo: {}", nullFoo.is_some());
}
```

I think for TSBC, it's sensible to merge `null` and `undefined` however a variable _must_ be declared to be nullable. The compiler will mimic `tsc` and fail to compile if a potentially `null` value was accessed without checking for `null`.

```typescript
function main() {
  const hasFoo: number | null = 0
  const nullFoo: number | null = null

  console.log(`hasFool: ${hasFoo != null}`)
  console.log(`nullFoo: ${nullFoo != null}`)
}
```
I am not sure how this model will look when completing an operation like parsing json, though.

> nan values

Can `NaN` values occur outside of parsing from a string? My expectation would be that if a `stringToNumber()` operation occurred and the result was not a number, it would produce an error and assign a 0 value to the variable.

Below is somewhat Go-like but serves to illustrate the idea.
```typescript
const [foo, error] = stringToNumber('not a number')
if (err != null) {
  console.log('failed to parse string to number')
  return
}
console.log(foo)
```

**Comment by Isaac-Leonard** [comment]
I agree with merging null and undefined, I think the optional api works too though could be implemented later on on top of null.
Would null be its own type as it half is now?
That would allow for simply allowing it threw union types and not add to much extra complexity.
TS also has the !: operator so you can do
let x!=4;
x=null;

Nan values can be produced from string concatenation and parsing, division by 0 and a couple other numerical oddities and probably some other weird way I'm forgetting.
I feel like the example you gave leaves room for forgetting or mishandling the error and throwing an exception might be the safer route to go.
Alternatively returning null could be an option though that feels a bit gross.
I guess this also brings up the Infinity and -Infinity values too.
Do you think it would be a good idea for typescript bc to implement those in some way?

**Comment by alshdavid** [comment]
> Would null be its own type as it half is now?

I just added a page introducing `null` into the readme. Feel free to suggest alternatives but basically `null` would be a built-in object and not a null pointer.

```typescript
const n = null
console.log(n.toString())
```
_Every builtin will have a `toString()` method to help print functions know how to display them_

> I feel like the example you gave leaves room for forgetting or mishandling the error and throwing an exception might be the safer route to go.

I definitely agree though I am torn on exceptions at this stage. My understanding is exceptions require additional runtime code to be shipped increasing the size of the binary. The question is if they provide enough value to warrant the overhead.

At this stage I think that I will let the application panic and die for situations like divide by 0 - only so I can get a prototype out and kick up more minds into answering these design questions

**Comment by alshdavid** [comment]
For the first version I will just panic if a bad numeric operation is attempted. Parsing will result in an error response in the return value of the parse function - however we may change this in future with the addition of exceptions: https://github.com/alshdavid/BorrowScript/issues/11
