### ISSUE TITLE
Does this project need a better name?

### ISSUE THREAD

**Issue by alshdavid** [alshdavid/BorrowScript#14]
TypeScriptBC stands for TypeScript (with) Borrow Checker. The name is descriptive, but also misleading as it's not _really_ TypeScript and not compatible with anything in the TypeScript/JavaScript world.

While the language takes the type system, majority of the language and module syntax from TypeScript - it's quite different when you apply a borrow checker to it.

I was trying to think of Rust puns. I had the idea of "Oxide", "Oxie" or "OxieLang" and having a cute cartoon Ox as a mascot.

![image](https://user-images.githubusercontent.com/12656294/135456332-49ba4a99-9cc7-478c-88f3-abd348663da2.png)
_Not this image specifically, but similar_

But then I thought that people might call newcomers Oxen and that's kinda weird. 

Honestly, if I were good at naming things, I wouldn't have created a repo called TypeScriptBC 😄

**Comment by differentsmoke** [comment]
TypeScript is called that because it adds Types to JavaScript. By that same logic you could call this language BorrowScript?

**Comment by SuperSonicHub1** [comment]
BorrowScript works so well since we're borrowing from TypeScript and Rust.

**Comment by alshdavid** [comment]
Haha dude, that's inspired. I'm happy with renaming this project to BorrowScript

**Comment by mindplay-dk** [comment]
It's not really a *scripting* language anymore though, is it? 😏
