### ISSUE TITLE
Syntax compatibility

### ISSUE THREAD

**Issue by trusktr** [alshdavid/BorrowScript#18]
As I mentioned in #13, it might be beneficial in gaining users by having tooling that already works.

Related to that, what about using compatible syntax?

F.e. instead if

```js
function readText(read value: string): void {
  console.log(value)
}
```

it could be

```js
// Using currently-invalid syntax that TypeScript knows how to parse, and might be compatible with upcoming EcmaScript specs
// @ts-ignore function decorator
@read('value')
function readText(value: string): void {
  console.log(value)
}

//

// Using TypeScript comment directive syntax:
// @read value
function readText(value: string): void {
  console.log(value
}

// Or maybe even
function readText(/*@read*/ value: string): void {
  console.log(value)
}
```

This will help to 

> offer the ergonomics of the TypeScript language.

because if someone can open a BS project in VS Codes and it just works out of the box today. F.e. hover and see type tooltip, or run Go To Definition shortcut to navigate code, etc, that'll be really helpful for developer ergonomics.

Those benefits can outweigh the slightly more verbosity. Tapping into existing tooling support would make this more highly adoptable out of the box right now.

**Comment by SuperSonicHub1** [comment]
I like the decorator, but I still think having custom keywords would be
best.

**Comment by alexvargasbenamburg** [comment]
I not like it, I really prefer the custom keywords, and is not super complicated to add/learn. The other options add more text that can be easily forget.

**Comment by alshdavid** [comment]
> because if someone can open a BS project in VS Codes and it just works out of the box today. F.e. hover and see type tooltip, or run Go To Definition shortcut to navigate code, etc, that'll be really helpful for developer ergonomics.

I am in agreement with you. I would like to avoid writing a language server (for highlighting and intellisense) early in the project if I can. Thanks for the suggestions too. I believe there may be a solution here though it's imperfect.

> [Decorator example]
Decors occupy a certain meaning and I would rather not have magic compiler decorators that live outside that definition. Your suggestion to use comments might work though.

```typescript
function readText(/*@read*/ value: string): void {
  console.log(value)
}
```

Thinking about the problem like a "migration" of sorts, the compiler might be able to parse both.
```typescript
function readText(read value: string): void {}
function readText(/*@read*/ value: string): void {}
```
This would allow us to use the TypeScript language server (for syntax highlighting) and move to our own language server at a later date. 

### There are limitations though

For example, in Rust, callbacks do no automatically capture variables in their outer scope. One must explicitly move the values into a child scope from a parent scope.

Where in TypeScript you would say
```typescript
const a = 'foo'

setTimeout(() => {
   console.log(a)   // In Rust you must import "a" into this scope 
})
```
In rust you must
```rust
let a = String::from("foo");

set_timeout(&( move || { // lambda function decorated with a "move"
  println!("{}", a); // the "move" will automatically change ownership of used values from an outer scope
}));

let a = String::from("foo"); // You can now redeclare "a" because it has been moved out
```
To emulate this I have introduced "ownership gates" that allow you to describe the variables you wish to import from an outer scope into your function. 

```typescript
function<T>(args)[ownership gate] { code block }
```

Which looks like this:
```typescript
const a = 'foo'

setTimeout(()[move a] => { // import a from outside
   console.log(a)
})
```

We could achieve this with a comment, but we wouldn't get any vscode errors.
```typescript
setTimeout(()/*@og[move a]*/ => {})
```

It's a decent suggestion and lets us write code in VScode today and even perhaps use an existing TypeScript AST parser

**Comment by alshdavid** [comment]
In an effort to start working on a compiler for this language - I feel it best we just roll out with our own syntax. I'd rather not have to have a migration pathway away from TypeScript's language server to our own.

If the language is worth its weight and a compiler ratifies the language rules - I feel confident that the community will pitch in to help with things like a language server

**Comment by trusktr** [comment]
Personally I was hoping the syntax (`read`, `write`, `[gate]`) could be entirely implicit, because, what would be powerful is being able to take the same TypeScript code and compile to either JS (a workable subset of course), or WebAssembly.
