### ISSUE TITLE
[proposal] How to deal with passing parameters into child functions from lexical scopes?

### ISSUE THREAD

**Issue by alshdavid** [alshdavid/BorrowScript#2]
Given this example in vanilla TypeScript

```typescript
const foo = 'foo'

function bar() {
  console.log(foo)
}
```
The `bar` function has untethered access to its outer scope and thus can access `foo`. This conflicts with the notion of a borrow checker where `foo` must be explicitly passed into the `bar` scope and its permissions described.

Perhaps adding a seperate set of parameters to denote scope transfer would suffice
```typescript
function<T>(...args)[...args]: U { /* code */ }
```

example:
```typescript
const foo = 'foo'

function bar()[read foo]: void {
  console.log(foo)
}
```

**Comment by SuperSonicHub1** [comment]
One question: is `foo` a compile-time constant? If so, why can't the value simply be inlined? If we're instead concerned about values assigned with `let`, I see no reason why the proposed syntax wouldn't work just fine; it in fact reminds me a lot of a Java function's exception contract.

**Comment by alshdavid** [comment]
Perhaps my example is overly simplified, this might better represent the case:

```typescript
function main() {
  let foo = 'Hello'

  function bar()[write foo] {
    foo.push(' World')
  }

  console.log(foo) // "Hello"
  bar()
  console.log(foo) // "Hello World"
}
```
`foo` is a dynamic `string` (char vector) and there is a nested scope that wants access to it. While in the above case you could just pass the value as a parameter of the function - in the case of callback functions there is no such mechanism.

**Comment by alshdavid** [comment]
Related solution:

https://github.com/alshdavid/BorrowScript/issues/3
