### ISSUE TITLE
Assemblyscript

### ISSUE THREAD

**Issue by mindplay-dk** [alshdavid/BorrowScript#21]
What would be the key difference between [AssemblyScript](https://www.assemblyscript.org/) and this?

Is it mainly the borrow checker?

I wonder if AS would make a good jumping-off point for this language? They've already put some years of hard work into the compiler itself, which might could shave considerable time off to get this language off the ground?

(Or if the AS maintainers might even be open to taking their language in that direction?)

**Comment by SuperSonicHub1** [comment]
AssemblyScript is solely focused on WebAssembly, while BorrowScript
intends to target most of the domains Rust targets, including the web.
The borrow checker is pretty much why this project exists.

**Comment by alshdavid** [comment]
Well said SuperSonigHub1. I'll like to add that the borrow checker also comes with it distinct advantages, a lot of which are particularly well suited to the web platform as it does battle with native applications for supremacy.

Things like; uniquely fearless multi-threading + concurrency, tiny binaries and fast load times

**Comment by mindplay-dk** [comment]
Right, so the back-end would be substantially different from that of AssemblyScript.

The lexer, parser, AST, semantics, etc. still might be useful as a jumping off point? That's a lot of work.

I'd like to see this language actually exist, is why I bring this up, heh - I know how long this type of work takes. 🙂

**Comment by alshdavid** [comment]
Yeah it's a lot of work and I agree that borrowing as much work from others would be very helpful. Will consider it as I begin putting together the starting point
