### ISSUE TITLE
Prefer message passing techniques  for inter thread communication

### ISSUE THREAD

**Issue by Isaac-Leonard** [alshdavid/BorrowScript#27]
It might be a good idea to limit. the power of threads to prefer message passing over modifying variables and directly controlling mutexes and semaphores.
This would mean the borrow checker would be simpler and likely improve the clarity of code.
Currently typescript allows this with web workers and nodes worker threads however these require a lot of boilerplate to make useful.
Instead of this would it be possible to instantiate a thread in the currently outlined method but have a way to pass variables in and out of the thread.
This could be done with some sort of thread.pass(move var:something):void; method.
and some sort of promise based response method that the passing thread can wait on to regain control of the var variable.

It might also be useful to implement some sort of stream interface on the Thread class so that they can emit values that get acted upon by a callback listener function in another thread.

**Comment by alshdavid** [comment]
Just like in Rust, you can do either. The language makes both choices safe, it's up to you to pick your preference as a project author.
