### ISSUE TITLE
Duct typing with static compilation

### ISSUE THREAD

**Issue by Isaac-Leonard** [alshdavid/BorrowScript#28]
In the structural typing file you mention that achieving duck typing with the language being statically compiled.
Would it not be possible to use type inference for any object declarations?
If you enforce type boundaries on functions then you could simply check if a variables inferred shape matches whenever attempting to pass it to a function.
I believe go does something similar to this where classes don't explicitly declare what interfaces they implement but to be passed to a function that requires a specific interface it must have all of the matching methods.
We could do the same here but just with raw objects.

**Comment by alshdavid** [comment]
It's possible but difficult. I think it's a project to tackle down the road. For now all object definitions must have an accompanied `type` definition.
