### ISSUE TITLE
Will BorrowScript target microcontrollers? 

### ISSUE THREAD

**Issue by ceremcem** [alshdavid/BorrowScript#44]
Do "Embedded applications" within the Readme/Audiences section also cover microcontrollers?

**Comment by SuperSonicHub1** [comment]
Realistically, BorrowScript should be able to target any platform Rust can,
so I can't see why we can't support microcontrollers.

**Comment by ceremcem** [comment]
So, the BorrowScript compiler will be a [transcompiler](https://en.wikipedia.org/wiki/Source-to-source_compiler). Is that correct?

**Comment by alshdavid** [comment]
Coming back to this:

I will be targeting LLVM IR for the compiler. This means that the code should be able to target embedded architectures. As for bindings to control the various pins, they will have to be provided in libraries likely wrapping FFI calls to C.

I would like to include these binding wrapper libraries in the standard library.

```typescript
import pi from "@std/embedded/pi-pico"
```
