### ISSUE TITLE
A better way to handle Errors

### ISSUE THREAD

**Issue by sirlordt** [alshdavid/BorrowScript#45]
I believe is good idea keep try catch block handler and keep both ways to handle errors (inline/try catch).

Sometime interrupt the code execution and handle in central place is a good idea
Old style try catch
```
try {

  //Error here
  parseInt( "Not a number" )

}
catch ( error ) {

   // handle error

}
```

New style 1

Could be a good idea use **try** before call function. In order not propagate the error to superior scope and not break the code execution.

```
const [ value, error ] = try parseInt( "Not a number" )

if ( error != null ) {

  // handle error

}
```

New style 2
```
const [ value, error ] = try {  

 let x = parseInt( "Not a number" )

 return 10 / x //This return is to exit from try block scope, and assign the value variable in the superior scope.

}

if ( error != null ) {

  // handle error

}
```

**Comment by alshdavid** [comment]
Thanks for these suggestions, using `try` as a keyword to suppress throwing a function is a really interesting idea.

Error handling is something I have been wondering about a lot. I would like the binary outputs to be a small as possible and exceptions are expensive from a size and computation aspect - but it's undeniable that they are useful.

I think that the most pragmatic approach is just to support `try`/`catch` blocks but perhaps at a later date. It's easy enough to add onto the existing language specification so it's not really pressing and I'd like to begin working on the compiler.

Closing for now, please feel free to reopen under the discussion tab. Once we have a V1 language I think it will be wise to start operating off of a language proposal model similar to Go and ECMAScript
